import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Meme Generator Application</title>
        <meta
          name="description"
          content="Remote Landing Page Generated by Next App and Typescript"
        />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <meta property="og:title" content="remote-work-page"/>
        <meta property="og:type" content="landing page" />
        <meta property="og:description" content="remote.description" />
        <link rel="icon" href="/images/remoteIcon.png" />
      </Head>
 
    </div>
  )
}

export default Home
